### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by gsc2001**

### CODE REVIEW

**Comment by tichnas** [comment]
Should we delete `.eslintcache`?

**Comment by gsc2001** [comment]
Yes, it is advised online to add it to .gitignore

**Comment by tichnas** [comment]
I've a doubt, if you added it to gitignore then how your git is detecting that the file is deleted?

**Comment by gsc2001** [comment]
I first deleted the file then i added it to .gitignore

**Review by tichnas — APPROVED** [review]

**Pull request merged**
